# Generated by Django 4.2 on 2023-04-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
